// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFTOAVpyqh5Xz-zaftCzDnLt8yIJtxsrI',
    appId: '1:1014421717446:web:f614917f71cbfbd598b2c7',
    messagingSenderId: '1014421717446',
    projectId: 'loginsignup-b1dc9',
    authDomain: 'loginsignup-b1dc9.firebaseapp.com',
    storageBucket: 'loginsignup-b1dc9.appspot.com',
    measurementId: 'G-2T3012VP97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMn_SkBiGlm1EHmsIKGcJPVo05i4WXkno',
    appId: '1:1014421717446:android:5ae5be855591e3ba98b2c7',
    messagingSenderId: '1014421717446',
    projectId: 'loginsignup-b1dc9',
    storageBucket: 'loginsignup-b1dc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGLyvDBTTp_8euLTWP0WpDVV9g88WbRPc',
    appId: '1:1014421717446:ios:a90a8585dc341eac98b2c7',
    messagingSenderId: '1014421717446',
    projectId: 'loginsignup-b1dc9',
    storageBucket: 'loginsignup-b1dc9.appspot.com',
    iosBundleId: 'com.example.loginsignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGLyvDBTTp_8euLTWP0WpDVV9g88WbRPc',
    appId: '1:1014421717446:ios:a90a8585dc341eac98b2c7',
    messagingSenderId: '1014421717446',
    projectId: 'loginsignup-b1dc9',
    storageBucket: 'loginsignup-b1dc9.appspot.com',
    iosBundleId: 'com.example.loginsignup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFTOAVpyqh5Xz-zaftCzDnLt8yIJtxsrI',
    appId: '1:1014421717446:web:76b518178b7189f398b2c7',
    messagingSenderId: '1014421717446',
    projectId: 'loginsignup-b1dc9',
    authDomain: 'loginsignup-b1dc9.firebaseapp.com',
    storageBucket: 'loginsignup-b1dc9.appspot.com',
    measurementId: 'G-LEKH55EV8T',
  );
}
